# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- build
- test
- deploy
- review
- dast
- staging
- canary
- production
- incremental rollout 10%
- incremental rollout 25%
- incremental rollout 50%
- incremental rollout 100%
- performance
- cleanup

# jobs for build stage
# Override default 'build' job
build:
  stage: build
  script: 
    - echo 'Create the package...'
    - "tar -C .. -czf ${CI_COMMIT_SHORT_SHA}_package.tgz ${CI_PROJECT_NAME} \
        --exclude ${CI_PROJECT_NAME}/.git \
        --exclude ${CI_PROJECT_NAME}/.gitignore \
        --exclude ${CI_PROJECT_NAME}/.gitlab-ci.yml \
        --exclude ${CI_PROJECT_NAME}/README.md"
  artifacts:
    paths:
      - ${CI_COMMIT_SHORT_SHA}_package.tgz
  
# jobs for test stage
# Default 'test' job
test:
  stage: test
  script:
    - echo 'this is the test job.'
    - ls -la

check-php-syntax:
  stage: test
  image: php:alpine  # Use latest version of php:alpine for testing.
  script:
    # install phplint to speed this up?
    - php -l config.php
    - php -l index.php
    - php -l submit.php
    - php -l api/v1/index.php
    - php -l api/v1/sat_info.php

check-php-version:
  stage: test
  image: php:alpine # Use latest version of php:alpine for testing.
  script:
    - php --version

# Disable default 'container_scanning' job
# Can use this if we end up deploying as docker image vs. static code
container_scanning:
  stage: test
  when: manual

include:
  - template: Auto-DevOps.gitlab-ci.yml
