# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- build
- test
- deploy
- review
- dast
- staging
- canary
- production
- incremental rollout 10%
- incremental rollout 25%
- incremental rollout 50%
- incremental rollout 100%
- performance
- cleanup

# jobs for build stage
# Override default 'build' job
build:
  stage: build
  script: 
    - echo 'Create the package...'
    - export PKGNAME=`echo "$CI_COMMIT_SHORT_SHA"_package`
    - tar --exclude .* --exclude $PKGNAME.tgz -czf $PKGNAME.tgz .
    - ls -la
  artifacts:
    paths:
      - 'satellite-status/$PKGNAME.tgz'
  
# jobs for test stage
# Default 'test' job
test:
  stage: test
  script:
    - echo 'this is the test job.'

sast:
  stage: test

check-php-syntax:
    stage: test
    image: php:alpine  # Use latest version of php:alpine for testing.
    script:
        - php -l config.php
        - php -l index.php
        - php -l info.php
        - php -l submit.php

check-php-version:
  stage: test
  image: php:alpine # Use latest version of php:alpine for testing.
  rules:
    - when: always
  script:
    - php --version

# Disable default 'container_scanning' job
container_scanning:
  stage: test
  when: manual

include:
- template: Auto-DevOps.gitlab-ci.yml